<#ftl output_format="HTML">
<#assign root = noticeView.viewTemplateRoot />
<#assign noticeName = noticeView.name />

<#-- Identation macro to make the output more readable. -->
<#assign indent = 2 />
<#macro ind depth>${""?left_pad(depth * indent)}</#macro> 

<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>HTML5 notice view: ${noticeName}</title>
  <meta name="description" content="A simple HTML5 view of a notice, generated by eForms Notice Viewer">

<style>
body {
  font-size: 16px;
}

.notice-view-node {
  margin-left: 2em;
  border-left: dotted 1px #bbb;
  border-top: dotted 1px #bbb;
  padding: 0.2em;
}

.notice-view-node-depth-1 {
  font-weight: bold;
}
.notice-view-node-depth-2 {
  font-weight: bold;
}
</style>

</head>
<body>
  <!-- This content was generated by eForms Notice Template (using freemarker). -->
  <!-- View notice information. -->
  <section id="notice-view">
    <h1 class="notice-view-name">${noticeView.name}</h1>
    <h2 class="notice-view-description">${noticeView.description}</h2>

    <!-- View notice nodes. -->
  <#macro processTreeRecursive node depth>
  <#assign nodeDepth = node.depth />
  <@ind depth/><section id="${node.id}" class="notice-view-node notice-view-node-depth-${nodeDepth}">
  
    <@ind depth/><h${nodeDepth}><pre>${node.template}</pre></h${nodeDepth}>
    <@ind depth/><div class="notice-view-child-nodes">
    
    <#list node.childNodes as childNode>
      <#-- The node depth is not always the same as the identation depth -->
      <#-- Here we add 2 because 1 for depth due to nesting, 1 for the child container tag. -->
      <@processTreeRecursive node=childNode depth=(depth + 2) />
    </#list>
    <@ind depth/></div>
    
  <@ind depth/></section>
  </#macro>
  <@processTreeRecursive node=root depth=0/>

  </section>

</body>
</html>
