<#ftl output_format="HTML">
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>A simple HTML5 view of a notice</title>
  <meta name="description" content="A simple HTML5 view of a notice, generated by eForms Notice Viewer">

  <!--<link rel="icon" href="/favicon.ico">-->
  <!--<link rel="icon" href="/favicon.svg" type="image/svg+xml">-->
  <!--<link rel="apple-touch-icon" href="/apple-touch-icon.png">-->
  <!--<link rel="stylesheet" href="css/styles.css?v=1.0">-->
  
<style>
.notice-view-node {
  margin-left: 2em;
}
</style>
  
</head>
<body>
  <!-- This content was generated by eForms Notice Template (using freemarker). -->

  <!-- View notice information. -->
  <h1 class="notice-view-name">${noticeView.name}</h1>
  <h2 class="notice-view-description">${noticeView.description}</h2>

  <#assign root = noticeView.viewTemplateRoot />
  <#macro processTreeRecursive node>
  
  <div id="${node.id}" class="notice-view-node">
    <pre>${node.template}</pre>
    <#list node.childNodes as childNode>
      <pre>${childNode.id}</pre>
      <@processTreeRecursive node=childNode />
    </#list>
  </div>
  
  </#macro>
  
  <!-- View notice nodes. -->
  <@processTreeRecursive node=root />
</body>
</html>
