name: Build the project
on:
  push:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build package
        run: mvn --batch-mode -DM2_SETTINGS=.github/workflows/settings.xml clean install # Property "M2_SETTINGS" is used by the SDK downloader in tests.
